-- MySQL Script generated by MySQL Workbench
-- Tue May 31 16:10:33 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema BD_BankAccountManagement
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BD_BankAccountManagement
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BD_BankAccountManagement` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `BD_BankAccountManagement` ;

-- -----------------------------------------------------
-- Table `BD_BankAccountManagement`.`tb_people`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_BankAccountManagement`.`tb_people` (
  `id_people` BIGINT NOT NULL AUTO_INCREMENT,
  `birth_date` DATE NOT NULL,
  `cpf` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_people`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `BD_BankAccountManagement`.`tb_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_BankAccountManagement`.`tb_account` (
  `id_account` BIGINT NOT NULL AUTO_INCREMENT,
  `account_type` VARCHAR(255) NOT NULL,
  `active_flag` VARCHAR(255) NOT NULL,
  `balance` DOUBLE NOT NULL,
  `created_date` DATE NULL DEFAULT NULL,
  `withdrawal_limit` DOUBLE NOT NULL,
  `people_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id_account`),
  INDEX `fk_people` (`people_id` ASC) VISIBLE,
  CONSTRAINT `fk_people`
    FOREIGN KEY (`people_id`)
    REFERENCES `BD_BankAccountManagement`.`tb_people` (`id_people`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `BD_BankAccountManagement`.`tb_transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_BankAccountManagement`.`tb_transaction` (
  `id_transaction` BIGINT NOT NULL AUTO_INCREMENT,
  `account_id` BIGINT NULL DEFAULT NULL,
  `transaction_date` DATE NULL DEFAULT NULL,
  `value` DOUBLE NOT NULL,
  PRIMARY KEY (`id_transaction`),
  INDEX `fk_account` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `BD_BankAccountManagement`.`tb_account` (`id_account`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
